version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      PSQL: postgres://user:password@db:5432/mydatabase
    restart: unless-stopped
    volumes:
      - ./uploads:/app/server/uploads

volumes:
  postgres_data:
